version: "3.3"

services:
  db:
    image: postgres:10.15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: booker
      POSTGRES_PASSWORD: booker
      POSTGRES_DB: booker
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file: ./app/.env
    ports:
      - 3000:3000

volumes:
  db_data:
